### ISSUE TITLE
Class Activation Map

### ISSUE THREAD

**Issue by ldlshizhu** [JihyongOh/DeMFI#1]
Thank you for your contribution. Can you upload the source code containing the "Class Activation Map"

**Comment by JihyongOh** [comment]
@ldlshizhu
Hi, thank you for your interest, what does "CAM" exactly mean in your context? 
This task is not for classification so there is no CAM for a certain class.
 Does it mean a feature map visualization as Fig. 6 in the paper?

**Comment by ldlshizhu** [comment]
I'm sorry I didn't make it clear. As you can understand, "CAM" is a well-known class activation tool, which can well reflect the areas that our network pays attention to (such as blurred people in motion in photos). Of course, it's very convincing for you to visualize in other ways (such as Figure 6 and Figure 7)! So can you kindly publish the code of feature graph visualization when you publish the source code?
Have a nice life! Look forward to your work.

**Comment by ldlshizhu** [comment]
I'm sorry I didn't make it clear. As you guessed, "CAM" is a well-known class activation tool, which can well reflect the areas that our network pays attention to (such as blurred people in motion in photos). Of course, it's very convincing for you to visualize in other ways (such as Figure 6 and Figure 7)! So can you kindly publish the code of feature graph visualization when you publish the source code?
Have a nice life! Look forward to your work.

**Comment by ldlshizhu** [comment]
This is the project address of cam, so you can have a look if you are interested   ：D
https://github.com/jacobgil/pytorch-grad-cam

**Comment by JihyongOh** [comment]
@ldlshizhu 
Thank you for your recommendation, I will consider it when I upload it :)
