### ISSUE TITLE
Encountered several problems when running test_custom

### ISSUE THREAD

**Issue by 98mxr** [JihyongOh/DeMFI#3]
I need to change the type of the parameter multiple_MFI from type=list in the code to type=int. 

Then I encountered the following error.

> Traceback (most recent call last):
  File "C:\Users\98mxr\Downloads\DeMFI\main.py", line 1198, in <module>
    main()
  File "C:\Users\98mxr\Downloads\DeMFI\main.py", line 361, in main
    test_custom(final_test_loader, model_net,args, device,
  File "C:\Users\98mxr\Downloads\DeMFI\main.py", line 1137, in test_custom
    patch_forward_DeFInet_itr(model_net, input_frames, None, t_value, num_update, patch,
  File "C:\Users\98mxr\Downloads\DeMFI\utils.py", line 1403, in patch_forward_DeFInet_itr
    Sharps_prime, Sharps_final, flow_predictions, occ0_predictions, two_blurry_inputs = model_net(input_frames[:, :, :, H_low_ind:H_high_ind, W_low_ind:W_high_ind],
  File "C:\Users\98mxr\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\98mxr\Downloads\DeMFI\DeMFInet.py", line 78, in forward
    Agg1 = self.Refine_Module(Agg1) + torch.cat(
  File "C:\Users\98mxr\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\98mxr\Downloads\DeMFI\DeMFInet.py", line 598, in forward
    out = torch.cat((out, enc1), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 224 but got size 225 for tensor number 1 in the list.

I am afraid I cannot solve this problem and submit it to the code owner for processing.

English is not my native language, please accept my apology if there is anything wrong with the above statement.

**Comment by JihyongOh** [comment]
@98mxr 
Hi, thank you for your interest.
What is the input resolution for the frames?

**Comment by 98mxr** [comment]
> @98mxr Hi, thank you for your interest. What is the input resolution for the frames?

800*450, The equipment tested is very limited, it is difficult to support too large resolution.

**Comment by JihyongOh** [comment]
I see, please add '--patch_boundary 32' then it will work:)

**Comment by 98mxr** [comment]
When I add type=int to patch_boundary (And replaced my GTX970M 3G with a Nvidia Tesla T4), everything is correct.

```
parser.add_argument('--patch_boundary', default=0,
parser.add_argument('--patch_boundary', type=int, default=0,
```
I have sorted out the requirements list except for torch, torchvision and numpy and pillow installed at the same time. I hope it will be helpful to everyone.

```
opencv-python
torchinfo
tensorboardX
six
pandas
matplotlib
scikit-image
```

**Comment by JihyongOh** [comment]
@98mxr 
Thank you, to reflect your comment,
I have modified several types of the arguments and newly add a requirements.txt file as well.
https://github.com/JihyongOh/DeMFI/blob/db24554c716007518c0716a9737ae5fb14456ca9/requirements.txt#L1-L12

**Comment by 98mxr** [comment]
Thank you very much for the attention of the developers, I have not encountered any problems now.
