### ISSUE TITLE
Pretrained Model Link

### ISSUE THREAD

**Issue by SpaceLlama2000** [JihyongOh/DeMFI#4]
Hello, I noticed that the pretrained model weight link points to "https://www.dropbox.com/s/xj2ixvay0e5ldma/XVFInet_X4K1000FPS_exp1_latest.pt" rather than DeMFI-Net , would it be possible to correct the link?

**Comment by JihyongOh** [comment]
@SpaceLlama2000 
Thank you for your interest and finding a typo!
I am sorry to mistakenly write the wrong link so I have fixed it now.

**Comment by SpaceLlama2000** [comment]
Thank you for sharing this work and fixing that quickly :)
