### ISSUE TITLE
Colab demo?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [JihyongOh/DeMFI#5]
Thanks for sharing this fantastic work.
Would you consider making a google Colab notebook for the less technically inclined like myself to try this?

**Comment by JihyongOh** [comment]
@noobtoob4lyfe 
Thank you for your interest!
Unfortunately, I have never used Colab before, so it seems difficult to make it right now, sorry.

**Comment by noobtoob4lyfe** [comment]
thanks for your response.
