### ISSUE TITLE
How to test custom png sequence?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [JihyongOh/DeMFI#6]
I'm getting this error when I attempt to run main.py.
"File "C:\Users\importon\Documents\DeMFI-main\utils.py", line 533, in __init__
    raise (RuntimeError("Found 0 files in subfolders of: " + self.args.custom_path + "\n"))
RuntimeError: Found 0 files in subfolders of: './custom_path'"
![Capture](https://user-images.githubusercontent.com/43832374/149444238-b3487fe8-ba83-4651-8e73-9c8816c86f89.PNG)

 I've put my blurry images in the "scene1" folder.  Do I need to put anything in the "sceneN" folder?

**Comment by JihyongOh** [comment]
@noobtoob4lyfe 
you don't need to create or put anything to "sceneN" folder which is just example of the folder names. 
It is ok there is only one folder with arbitrary name.

**Comment by noobtoob4lyfe** [comment]
Thanks!  Would you have any idea why I'm getting this error?  My images are in the right folder in my screenshot above right?

"File "C:\Users\importon\Documents\DeMFI-main\utils.py", line 533, in init
raise (RuntimeError("Found 0 files in subfolders of: " + self.args.custom_path + "\n"))
RuntimeError: Found 0 files in subfolders of: './custom_path'"

**Comment by JihyongOh** [comment]
@noobtoob4lyfe 
1. This seems that the file path for '--custom_path' https://github.com/JihyongOh/DeMFI/blob/369e9221aa446c2840d1500ef79fa98140f7a36e/main.py#L123 is not valid or not recognized.
Have you run the code like a command as below?:
```bash
python main.py --gpu 0 --phase 'test_custom' --exp_num 1 --N_tst 3 --multiple_MFI 8 --custom_path './custom_path' --patch_boundary 32
```
There should be string notation (' ') that covers ./custom_path as ' ./custom_path'. 

2. Other possibility is that each scene must have at least 4 frames because DeMFI-Net takes **4 input frames** as described in the README.md.

**Comment by noobtoob4lyfe** [comment]
Thanks again for your help.  
This is the command I'm running.
"python main.py --gpu 0 --exp_num 1 --N_tst 3 --multiple_MFI 8 --custom_path './custom_path' --patch_boundary 32"

There are 7 frames in my png sequence.

**Comment by JihyongOh** [comment]
@noobtoob4lyfe 
I have successfully run the same setting as yours (one folder containing 7 frames) .
Did you include "--phase 'test_custom'"?
Can you show the all file names in your folder? (to check a file hierarchy)

**Comment by noobtoob4lyfe** [comment]
![image](https://user-images.githubusercontent.com/43832374/149473040-86dadcfc-9222-4e30-8ee1-f0cb182596e6.png)

When I include "--phase 'test_custom'" I get this error.
"main.py: error: argument --phase: invalid choice: "'test_custom" (choose from 'train', 'test', 'test_custom')"

So I modified line 31 of main.py to be "parser.add_argument('--phase', type=str, default='test_custom'," 
So it will default to "test_custom"

**Comment by noobtoob4lyfe** [comment]
Wait, if I remove all " ' " characters from the command it seems to be working.  
Very strange.  Could this be because I'm in an Anaconda env?

The the command that works for me is "python main.py --gpu 0 --phase test_custom --exp_num 1 --N_tst 3 --multiple_MFI 8 --custom_path ./custom_path --patch_boundary 32"

**Comment by JihyongOh** [comment]
@noobtoob4lyfe 
I agree with that it is strange working without " ' " and I have never seen before .
Codes has been run well under both Ubuntu and Windows with Anaconda env. 
Finally you have successfully run it, great:)

**Comment by noobtoob4lyfe** [comment]
Thanks again for your help!
